### ISSUE TITLE
update with rsdns-a.sh resulting in  line 144: test then Domain org not found.

### ISSUE THREAD

**Issue by jbrashear** [linickx/rsdns#27]
Here is the line:
./rsdns-a.sh -u MYACOUNT -a MYAPIKEY -n domain.org -i 192.168.1.1 -U

This produces:
./rsdns-a.sh: line 144: test: too many arguments

Domain org not found.

**Comment by linickx** [comment]
odd. Does `rsdns-list` work?

**Comment by jbrashear** [comment]
Yes list works but only brings back around 100

**Comment by linickx** [comment]
Interesting. 

Full Disclosure - This is a hobby project. I don't have any zones with more than ~10 records. 

Sound like something fundamental might break when working at scale. Are you able to provide any detail further on what's going on?

**Comment by jbrashear** [comment]
Im almost at my office. I will Screencast to show ya. I can write a script
to call one at a time all I need to do is update DNS records if you don't
mind helping me I don't mind paying you a little something I do have 2,000
domains I have to update IP addresses on all of them but again I only
needed to update one at a time I can script the rest

**Comment by linickx** [comment]
Hi, Sorry for the really late reply, day-job got in the way!

Initially I thought this was a problem with [pagination](https://developer.rackspace.com/docs/cloud-dns/v1/developer-guide/#document-general-api-info/pagination) which I have just fixed/implemented with 6c7ca863b6b3d37d46bbd92cdc8116456042dc5b so hopefully your list of > 100 records should work.

Looking closer at this issue you're trying to add a *naked* domain record did you try this from the [README.md](https://github.com/linickx/rsdns#rsdns-ash) ?

> To create a record with no prefix:
> ./rsdns-a.sh -u linickx -a 123456 -d linickx.com -n linickx.com -i 123.123.123.123

... with the `-U` on the end for your update.
