### ISSUE TITLE
TXT Records missing Data

### ISSUE THREAD

**Issue by linickx** [linickx/rsdns#31]
```
$ rsdns txt -d test.linickx.co.uk -n test.linickx.co.uk -D "v=spf1 include:_x.linickx.co.uk" -J
Job status is: RUNNING
Job status is: COMPLETED

 ID: TXT-11111 
 TYPE: TXT 
 NAME: test.linickx.co.uk 
 DATA: v=spf1 
 TTL: 86400 
 CREATED: 2016-05-06T08:28:30.000+0000 
 UPDATED: 2016-05-06T08:28:30.000+0000

$ 
```

The `-D` switch was `v=spf1 include:_x.linickx.co.uk` but record was created with `v=spf1` .. confirmed by dig.

```
$ dig +short -t TXT test.linickx.co.uk
"v=spf1"
$ 
```

**Comment by brianeclow** [comment]
It should also be noted, then you export a zone, the TXT Records are also not quoted. This causes problems for importing them into other services or use in conjunction with other tools.
