### ISSUE TITLE
Rackspace v2 API

### ISSUE THREAD

**Issue by brianeclow** [linickx/rsdns#35]
Is there currently any plan to update the tool to leverage the v2 API?

The v1.0 API has a known "limitation" with its export functionality, which makes it fail for zones with more then 300 records.

**Comment by linickx** [comment]
Hi, being honest it's not a high priority for me. I accept pull requests 😉

**Comment by brianeclow** [comment]
Fair enough. It isn't one of my priorities right now. Hopefully, I can put something together shortly.

**Comment by brianeclow** [comment]
I have transcended Rackspace. Closing.
