### ISSUE TITLE
Can't update root domain using rsdns-dc.sh

### ISSUE THREAD

**Issue by mattmansm** [linickx/rsdns#36]
I can't update the root (i.e. non-www) host of a domain using rsdns-dc.sh.

```
rsdns-dc.sh -n example.co.uk

Domain co.uk not found.

```

**Comment by RichieSM** [comment]
I occasionally get the same error on a .org domain. I think it's something in one of the functions, possibly this one: https://github.com/linickx/rsdns/blob/master/lib/func.sh#L156

**Comment by arnehortell** [comment]
By changing lib/func.sh to this it works for me.
Reason is substitution isnt consistent in bash over all architectures

function get_domain() {

  if [ -z $DOMAIN ]
      then
      HOST=`echo $1 | awk -F "." '{print $1}'`
      HOSTlen=${#HOST}

      HOSTlen=$(($HOSTlen + 1))
# the following line is removed
#      DOMAIN=${1:($HOSTlen)}
# and replaced by this

      DOMAIN=$1
  fi
}

**Comment by linickx** [comment]
Just pushed version 4.2, should fix this, thanks both for your posts!

**Comment by RichieSM** [comment]
Seems to still be an issue on the following when I'm trying to update my .org domain:
```lsb_release -a && bash --version
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```
I fixed it by setting `DOMAIN=$1` as in a previous comment.
