### ISSUE TITLE
Error  thrown in jq from rsdns-domain

### ISSUE THREAD

**Issue by blakilox** [linickx/rsdns#39]
rsdns-domain.sh always throws an error
jq: error (at <stdin>:1): Cannot iterate over null (null)
Environment
Centos 7.7 Latest yum installed jq
[root@au4 rsdns]# /root/rsdns/tests/run.sh

Output from rsdns Test Script
Begining Tests for Domain: test-24.com
Version 4.1
Job status is: RUNNING
Job status is: COMPLETED

 ID: 6637819
 NAME: test-24.com
 TTL: 600
 EMAIL: travis@test-24.com
 CREATED: 2020-01-27T21:25:45.000+0000
 UPDATED: 2020-01-27T21:25:45.000+0000
jq: error (at <stdin>:1): Cannot iterate over null (null)

Thanks

**Comment by linickx** [comment]
Ah, ok, looks like the JSON response is different now.
```
{"callbackUrl":"https://dns.api.rackspacecloud.com/v1.0/1abcdef1/status/2262cb21-xxxx-xxxx-xxxx-2b4cd81ac671","jobId":"2262cb21-xxxx-xxxx-xxxx-2b4cd81ac671","request":"{\"domains\": [{\"ttl\": 600,\"id\": null,\"name\": \"testdns.linickx.co.uk\",\"emailAddress\": \"linickx@email.com\",\"updated\": null,\"created\": null}]}","response":{"domains":[{"ttl":600,"accountId":1abcdef1,"id":6658120,"name":"testdns.linickx.co.uk","emailAddress":"linickx@gmail.com","updated":"2020-02-23T14:22:26.000+0000","created":"2020-02-23T14:22:26.000+0000"}]},"requestUrl":"https://dns.api.rackspacecloud.com/v1.0/1abcdef1/domains","verb":"POST","status":"COMPLETED"}
```

The Errors is [line 243](https://github.com/linickx/rsdns/blob/32c822f1d962795c4ba347a54fa73906f5a7f549/lib/func.sh#L243)

```
echo $RC | jq -r '(.response.domains[] | " NAMESERVERS: \(.nameservers[].name)")'
```

As `NAMESERVERS` are no longer included in the response, I'll just delete that line 🙃
