### ISSUE TITLE
BUG in func.sh -- with fix

### ISSUE THREAD

**Issue by mrpengy** [linickx/rsdns#41]
Found a bug in function get_recordid in func.sh. This will address several other issues others have posted about.

iNAME and iRECORDID variable assignments are incorrectly swapped. i.e. iNAME is being assigned the record id and vice versa. 

To fix, simply change $1 to $2 and $2 to $1 as below:

        if [ "$iTYPE" == "$RECORDTYPE" ]
        then
            iNAME=`echo $i  | awk -F "|" '{print $2}'`
            iRECORDID=`echo $i  | awk -F "|" '{print $1}'`

**Comment by linickx** [comment]
Merged #42 - Build Passed [[LINK](https://travis-ci.org/linickx/rsdns/builds/654071218)] ... looks like travis cannot read the secure variables for a PR `¯\_(ツ)_/¯` 

Many thanks for your efforts @mrpengy 👍 👍
